name: bench

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup-files
      run: ./uncompress.sh

    - name: rust/benchmark/v3
      run: cd rust/serdejsonbench && cargo build -r --examples && /usr/bin/time -pv -- ./target/release/examples/bench --console --times 10 --method v3

    - name: rust/benchmark/v2
      run: cd rust/serdejsonbench && cargo build -r --examples && /usr/bin/time -pv -- ./target/release/examples/bench --console --times 10 --method v2

    - name: rust/benchmark/v1
      run: cd rust/serdejsonbench && cargo build -r --examples && /usr/bin/time -pv -- ./target/release/examples/bench --console --times 10

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - run: cd dotnet/jsonbench && dotnet publish -c Release -o out && ls ./out
    
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: java/gson benchmark
      run: cd java/benchmark-gson && mvn clean package -DskipTests && /usr/bin/time -pv -- java -cp ./target/uber-benchmark-gson-0.0.1-SNAPSHOT.jar com.jsonbench.Main --console --times 10
    
    - name: java/jackson benchmark
      run: cd java/benchmark-jackson && mvn clean package -DskipTests && /usr/bin/time -pv -- java -cp ./target/uber-benchmark-jackson-0.0.1-SNAPSHOT.jar com.jsonbench.Main --console --times 10
