name: build-java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
    paths:
        - '.github/**-java.yml'
        - 'java/**'

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    - name: gson benchmark
      run: cd java/benchmark-gson && mvn clean package -DskipTests && java -cp .\target\uber-benchmark-gson-0.0.1-SNAPSHOT.jar com.jsonbench.Main --console --times 10
    